### ISSUE TITLE
Some general questions

### ISSUE THREAD

**Issue by nabadger** [lifechurch/k8s-deploy-helper#13]
Hi,

This set of tools is fantastic. I'm just playing with them at the moment, but for people want something simple, this is great.

I'm not really sure why Gitlab themselves don't push a lot of the scripts out into a separate image (it makes making new features available for all CI pipelines really simple).

I have some general questions.

### container image scanning

Would you consider a PR for this? It looks like Gitlab supports this and it's rather self contained (and optional)

### helm support

I'm not intending to use helm yet, but probably would when v3 comes out. I noticed that you included the `helm` binary, but no support for it. Do you think you would use it oneday, and want more features pushed into this repo to support it?

### canary deployments

I noticed that the canary deployment was named `canary` - do you not have issues with this conflicting when you deploy different applications into the same namespace?

### multi-cluster support

We are likely to have multiple clusters, such as `dev`, `qa`, `prod` - which means we would probably want to support multiple clusters. I imagine we could achieve this by extending the environment-vars passed in by Gitlab. Is this something you would be interested in as well (or do already?)

---

Thanks again.

**Comment by WillPlatnick** [comment]
Sorry for the late reply, notification settings were off.

Container Image Scanning - In the next release, we will have a stage that uses clair.

Helm Support - We've going to hold off on Helm templates until we switch to using a real programming language and adopt a real templating system rather than envsubst.

Canary Deployments - I am researching if we can reliably find a way to convert application manifests to canary deployments. As part of that, I imagine I'll just be prepending canary- to the name. We don't typically deploy multiple applications into the same namespace.

Multi-Cluster - This should be handled transparently with GitLab's multi-cluster support I believe, but I'm not sure. We're going to be moving towards a multi-cluster solution soon on our side.

**Comment by nabadger** [comment]
Awesome thanks
